const UserAction = {

  POST_USER_DATA: 'POST_USER_DATA',
  POST_USER_ERROR: 'POST_USER_ERROR',

  EDIT_USER_DATA: 'EDIT_USER_DATA',
  EDIT_USER_ERROR: 'EDIT_USER_ERROR',

  DELETE_USER_DATA: 'DELETE_USER_DATA',
  DELETE_USER_ERROR: 'DELETE_USER_ERROR',

  GET_USERS_DATA: 'GET_USERS_DATA',
  GET_USERS_ERROR: 'GET_USERS_ERROR',

  GET_USER_BY_ID_DATA: 'GET_USER_BY_ID_DATA',
  GET_USER_BY_ID_ERROR: 'GET_USER_BY_ID_ERROR'
  
};

export default UserAction;
